name: Monthly DB Backup

on:
  schedule:
    - cron: "0 0 1 * *" # First day of month at 00:00 UTC
  workflow_dispatch:     # Allows running manually

jobs:
  backup:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout this repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run backup script
      env:
        DATABASE_URL: ${{ secrets.RENDER_DATABASE_URL }}
      run: |
        python backup.py
        echo "BACKUP_FILE=$(ls backup-*.sql)" >> $GITHUB_ENV

    - name: Push backup to private backup repo
      env:
        TOKEN: ${{ secrets.BACKUP_REPO_TOKEN }}
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"
        git clone https://github.com/Henrycoding-design/SpaceappwebBackupStore.git out
        cp "$BACKUP_FILE" out/
        cd out
        git add .
        git commit -m "Backup $(date -u)"
        git push
